FROM nvcr.io/nvidia/tritonserver:25.04-py3

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    NVIDIA_VISIBLE_DEVICES=all \
    NVIDIA_DRIVER_CAPABILITIES=compute,utility \
    HF_HOME=/models-cache/huggingface

WORKDIR /opt/tritonserver

RUN env -u PIP_CONSTRAINT -u PIP_REQUIRE_HASHES pip install --no-cache-dir \
    numpy==1.26.4 \
    Pillow==10.4.0 \
    torch torchvision --index-url https://download.pytorch.org/whl/cu128 \
&& env -u PIP_CONSTRAINT -u PIP_REQUIRE_HASHES pip install --no-cache-dir \
    transformers==4.51.3 \
    einops==0.8.1 \
    kornia==0.8.1 \
    timm==1.0.21

CMD ["tritonserver", "--model-repository=/models"]
