services:
  remove-background-service:
    build:
      context: .
      dockerfile: server/Dockerfile
    env_file:
      - server/.env
    volumes:
      - training/runs:/training/runs:ro
    ports:
      - "8010:8010"
    restart: unless-stopped